package de.shopme.tools.knowledge.catalog

class CatalogNutritionReferenceParser(
    aliases: Map<String, String> = defaultAliases,
    private val nameNormalizer: CatalogNameNormalizer =
        CatalogNameNormalizer()
) {

    private val normalizedAliases =
        aliases.mapKeys { (key, _) ->
            nameNormalizer.normalize(
                key
            )
        }

    fun hasAlias(
        reference: String
    ): Boolean {

        val normalized =
            nameNormalizer.normalize(
                reference
            )

        return normalizedAliases.containsKey(
            normalized
        )
    }

    fun map(
        reference: String
    ): String {

        val normalized =
            nameNormalizer.normalize(
                reference
            )

        return normalizedAliases[normalized]
            ?: normalized
    }
    companion object {

        private val defaultAliases =
            mapOf(
                "apfel gala" to "apple",
                "apfel granny smith" to "apple",
                "vollmilch 35" to "milk",
                "hmilch 15" to "milk",
                "tomatenstuecke konserve" to "tomato",
                "bohnen rot konserve" to "kidney_beans",
                "ananasstuecke konserve" to "pineapple",
                "apfel" to "apple",
                "aepfel" to "apple",
                "banane" to "banana",
                "bananen" to "banana",
                "tomate" to "tomato",
                "tomaten" to "tomato",
                "milch" to "milk",
                "vollmilch" to "milk",
                "butter" to "butter",
                "brot" to "bread",
                "reis" to "rice",
                "nudeln" to "pasta",
                "pasta" to "pasta",
                "kartoffel" to "potato",
                "kartoffeln" to "potato",
                "karotte" to "carrot",
                "moehre" to "carrot",
                "brokkoli" to "broccoli",
                "spinat" to "spinach",
                "birne" to "pear",
                "kaffee" to "coffee",
                "tee" to "tea",
                "wasser" to "water",
                "lachs" to "salmon",
                "tofu" to "tofu",
                "mozzarella" to "mozzarella",
                "muesli" to "muesli",
                "erbsen dose" to "peas",
                "kichererbsen dose" to "chickpeas",
                "mais dose" to "corn",
                "kidneybohnen dose" to "kidney_beans",
                "erbsen konserve" to "peas",
                "mais konserve" to "corn",
                "kidneybohnen konserve" to "kidney_beans",
                "kichererbsen konserve" to "chickpeas",
                "weisse bohnen dose" to "white_beans",
                "linsen dose" to "lentils",
                "spinat tiefkuehl" to "spinach",
                "spinat tiefgekuehlt" to "spinach",
                "spinat tk" to "spinach",
                "brokkoli tiefkuehl" to "broccoli",
                "erbsen tiefkuehl" to "peas",
                "erbsen tk" to "peas",
                "tiefkuehlerbsen" to "peas",
                "reis langkorn" to "rice",
                "reis jasmin" to "rice",
                "basmatireis" to "rice",
                "schwarzer reis" to "rice",
                "wildreis bio" to "rice",
                "reis natur" to "rice",
                "sushireis" to "rice",
                "tofu natur" to "tofu",
                "linsen trocken" to "lentils",
                "mineralwasser still" to "water",
                "tee schwarz" to "tea",
                "tee gruen" to "tea",
                "joghurt natur" to "yogurt",
                "kaese gouda" to "gouda",
                "mozzarella light" to "mozzarella",
                "quitte" to "quince",
                "kirsche" to "cherry",
                "pflaume" to "plum",
                "zwetschge" to "plum",
                "mirabelle" to "mirabelle",
                "aprikose" to "apricot",
                "pfirsich" to "peach",
                "nektarine" to "nectarine",
                "erdbeere" to "strawberry",
                "himbeere" to "raspberry",
                "brombeere" to "blackberry",
                "heidelbeere" to "blueberry",
                "johannisbeere rot" to "red_currant",
                "johannisbeere schwarz" to "black_currant",
                "stachelbeere" to "gooseberry",
                "cranberry" to "cranberry",
                "orange" to "orange",
                "mandarine" to "mandarin",
                "clementine" to "clementine",
                "zitrone" to "lemon",
                "limette" to "lime",
                "grapefruit" to "grapefruit",
                "pomelo" to "pomelo",
                "mango" to "mango",
                "papaya" to "papaya",
                "ananas" to "pineapple",
                "kiwi" to "kiwi",
                "maracuja" to "passion_fruit",
                "passionsfrucht" to "passion_fruit",
                "litschi" to "lychee",
                "guave" to "guava",
                "wassermelone" to "watermelon",
                "cantaloupe" to "cantaloupe",
                "kokosnuss" to "coconut",
                "granatapfel" to "pomegranate",
                "feige" to "fig",
                "dattel" to "date",
                "trauben" to "grapes",
                "erdbeeren" to "strawberry",
                "kirschen" to "cherry",
                "melone" to "melon",
                "karotte" to "carrot",
                "karotten" to "carrot",
                "zwiebel" to "onion",
                "zwiebeln" to "onion",
                "gurke" to "cucumber",
                "gurken" to "cucumber",
                "paprika" to "bell_pepper",
                "blattspinat" to "spinach",
                "spinat" to "spinach",
                "kohlrabi" to "kohlrabi",
                "sellerie" to "celery",
                "knollensellerie" to "celery",
                "staudensellerie" to "celery",
                "rotkohl" to "red_cabbage",
                "rotkohl vakuumiert" to "red_cabbage",
                "weisskohl" to "white_cabbage",
                "brokkoli" to "broccoli",
                "blumenkohl" to "cauliflower",
                "rosenkohl" to "brussels_sprouts",
                "aubergine" to "eggplant",
                "zucchini" to "zucchini",
                "lauch" to "leek",
                "porree" to "leek",
                "fenchel" to "fennel",
                "rettich" to "radish",
                "radieschen" to "radish",
                "rucola" to "arugula",
                "eisbergsalat" to "iceberg_lettuce",
                "kopfsalat" to "lettuce",
                "feldsalat" to "lambs_lettuce",
                "tomaten konserve" to "tomato",
                "tomatenstuecke dose" to "tomato",
                "gruene bohnen" to "green_beans",
                "gruene bohnen konserve" to "green_beans",
                "bohnen dose" to "beans",
                "sojabohnen" to "soybeans",
                "naturjoghurt mild" to "yogurt",
                "frischkaese" to "cream_cheese",
                "frischkaese natur" to "cream_cheese",
                "sauerrahm" to "sour_cream",
                "creme fraiche" to "creme_fraiche",
                "schmelzkaese" to "processed_cheese",
                "kefir" to "kefir",
                "mozzarella" to "mozzarella",
                "quark" to "quark",
                "sahne" to "cream",
                "hafermilch" to "oat_milk",
                "haferdrink natur" to "oat_milk",
                "mandelmilch" to "almond_milk",
                "mandeljoghurt" to "almond_yogurt",
                "sojamilch" to "soy_milk",
                "sojadrink" to "soy_milk",
                "sojajoghurt" to "soy_yogurt",
                "sojajoghurt natur" to "soy_yogurt",
                "reismilch" to "rice_milk",
                "cashewmilch" to "cashew_milk",
                "cashewdrink" to "cashew_milk",
                "laktosefreie milch" to "milk",
                "ziegenmilch" to "goat_milk",
                "haferjoghurt" to "oat_yogurt",
                "rindfleisch" to "beef",
                "schweinefleisch" to "pork",
                "haehnchenbrust" to "chicken_breast",
                "haehnchenkeule" to "chicken",
                "putenfleisch" to "turkey",
                "lammfleisch" to "lamb",
                "hackfleisch gemischt" to "minced_meat",
                "kalbfleisch" to "veal",
                "rinderfilet" to "beef_fillet",
                "schweinefilet" to "pork_fillet",
                "salami" to "salami",
                "fleischwurst" to "sausage",
                "leberwurst" to "liver_sausage",
                "kochschinken" to "ham",
                "rindersalami" to "beef_salami",
                "jagdwurst" to "sausage",
                "teewurst" to "sausage",
                "weisswurst" to "white_sausage",
                "bratwurst" to "bratwurst",
                "mettwurst" to "sausage",
                "lachsfilet" to "salmon",
                "seelachsfilet" to "pollock",
                "thunfischdose" to "tuna",
                "thunfisch dose" to "tuna",
                "sardinen dose" to "sardines",
                "sardinen in oel" to "sardines",
                "forelle" to "trout",
                "garnelen" to "shrimp",
                "hering" to "herring",
                "scholle" to "plaice",
                "kabeljaufilet" to "cod",
                "aal" to "eel",
                "vollkornbrot" to "wholegrain_bread",
                "weizenbrot" to "bread",
                "baguette" to "baguette",
                "broetchen" to "bread_roll",
                "croissant" to "croissant",
                "mehrkornbrot" to "multigrain_bread",
                "dinkelbrot" to "spelt_bread",
                "roggenbrot" to "rye_bread",
                "toastbrot" to "toast_bread",
                "mischbrot" to "bread",
                "weizenvollkornmehl" to "whole_wheat_flour",
                "weizenmehl" to "wheat_flour",
                "roggenmehl" to "rye_flour",
                "haferflocken" to "oats",
                "polenta" to "polenta",
                "griess" to "semolina",
                "bulgur" to "bulgur",
                "hirse" to "millet",
                "quinoa" to "quinoa",
                "maismehl" to "corn_flour",
                "spaghetti" to "pasta",
                "penne" to "pasta",
                "fusilli" to "pasta",
                "tagliatelle" to "pasta",
                "lasagneplatten" to "pasta",
                "vollkornnudeln" to "wholegrain_pasta",
                "dinkelvollkornnudeln" to "wholegrain_pasta",
                "makkaroni" to "pasta",
                "reisnudeln" to "rice_noodles",
                "eiernudeln" to "egg_noodles",
                "bandnudeln" to "pasta",
                "kamutnudeln" to "pasta",
                "langkornreis" to "rice",
                "basmati reis" to "rice",
                "jasminreis" to "rice",
                "parboiled reis" to "rice",
                "wildreis" to "rice",
                "risottoreis" to "rice",
                "vollkornreis" to "brown_rice",
                "roter reis" to "rice",
                "klebreis" to "sticky_rice",
                "tomaten gehackt konserve" to "tomato",
                "bohnen konserve" to "beans",
                "spargel konserve" to "asparagus",
                "pfirsiche konserve" to "peach",
                "thunfisch konserve" to "tuna",
                "champignons konserve" to "mushrooms",
                "oliven konserve" to "olives",
                "gemuesemix tiefkuehl" to "mixed_vegetables",
                "gemuesemix tiefgekuehlt" to "mixed_vegetables",
                "tiefkuehlgemuese mix" to "mixed_vegetables",
                "tiefkuehlgemuesepfanne" to "mixed_vegetables",
                "gemuesepfanne fertiggericht" to "mixed_vegetables",
                "erdbeeren tiefkuehl" to "strawberry",
                "erdbeeren tiefgekuehlt" to "strawberry",
                "himbeeren tiefgekuehlt" to "raspberry",
                "beerenmix tiefgekuehlt" to "mixed_berries",
                "beerenmix tk" to "mixed_berries",
                "beerenmischung tiefkuehl" to "mixed_berries",
                "beerenmischung tiefgekuehlt" to "mixed_berries",
                "beerenmischung tk" to "mixed_berries",
                "tiefkuehlbeeren mix" to "mixed_berries",
                "moehren tiefkuehl" to "carrot",
                "chips" to "chips",
                "nuesse gesalzen" to "nuts",
                "popcorn" to "popcorn",
                "cracker" to "cracker",
                "reiswaffeln" to "rice_cakes",
                "studentenfutter" to "trail_mix",
                "geroestete mandeln" to "almonds",
                "salzstangen" to "pretzel_sticks",
                "chilinuesse" to "nuts",
                "pistazien" to "pistachios",
                "schokolade vollmilch" to "milk_chocolate",
                "zartbitterschokolade" to "dark_chocolate",
                "gummibaerchen" to "gummy_bears",
                "marzipan" to "marzipan",
                "keks" to "cookie",
                "waffeln" to "waffles",
                "lutscher" to "lollipop",
                "bonbons" to "candy",
                "nougat" to "nougat",
                "schokoriegel" to "chocolate_bar",
                "fruchtriegel" to "fruit_bar",
                "riegel muesliriegel" to "muesli_bar",
                "mineralwasser" to "water",
                "orangensaft" to "orange_juice",
                "apfelsaft" to "apple_juice",
                "traubensaft" to "grape_juice",
                "apfelbirnensaft" to "apple_pear_juice",
                "schwarztee" to "tea",
                "gruener tee" to "tea",
                "cola" to "cola",
                "bier" to "beer",
                "wein rot" to "red_wine",
                "pfeffer schwarz" to "pepper",
                "salz" to "salt",
                "paprikapulver" to "paprika",
                "kurkuma" to "turmeric",
                "kreuzkuemmel" to "cumin",
                "zimt" to "cinnamon",
                "muskatnuss" to "nutmeg",
                "oregano" to "oregano",
                "basilikum getrocknet" to "basil",
                "chilipulver" to "chili_powder",
                "olivenoel" to "olive_oil",
                "rapsoel" to "rapeseed_oil",
                "sonnenblumenoel" to "sunflower_oil",
                "walnussoel" to "walnut_oil",
                "leinoel" to "linseed_oil",
                "kokosoel" to "coconut_oil",
                "traubenkernoel" to "grapeseed_oil",
                "sesamoel" to "sesame_oil",
                "erdnussoel" to "peanut_oil",
                "avocadooel" to "avocado_oil",
                "tomatensauce" to "tomato_sauce",
                "mayonnaise" to "mayonnaise",
                "vegane mayonnaise" to "mayonnaise",
                "senf" to "mustard",
                "sojasauce" to "soy_sauce",
                "chilisauce" to "chili_sauce",
                "suesssaure sauce" to "sweet_sour_sauce",
                "barbecuesauce" to "barbecue_sauce",
                "currysauce" to "curry_sauce",
                "currypaste" to "curry_paste",
                "pesto gruen" to "pesto",
                "ketchup" to "ketchup",
                "salatdressing" to "salad_dressing",
                "tzatziki" to "tzatziki",
                "tempeh" to "tempeh",
                "seitan" to "seitan",
                "seitan natur" to "seitan",
                "seitan geschnetzeltes" to "seitan",
                "vegane burgerpatties" to "vegan_burger_patty",
                "vegane burger patties" to "vegan_burger_patty",
                "gemueseburger vegetarisch" to "vegetable_burger",
                "vegane wurst" to "vegan_sausage",
                "vegane butter" to "vegan_butter",
                "vegane kaesealternative" to "vegan_cheese",
                "vegane frischkaesealternative" to "vegan_cream_cheese",
                "vegane joghurtalternative" to "vegan_yogurt",
                "vegane sahnealternative" to "vegan_cream",
                "vegane schlagsahne" to "vegan_whipped_cream",
                "vegane gemuesebaellchen" to "vegan_vegetable_balls",
                "pommes frites" to "french_fries",
                "pommes frites tiefkuehl" to "french_fries",
                "tkpommes frites" to "french_fries",
                "fischstaebchen tiefkuehl" to "fish_fingers",
                "pizza margherita tiefkuehl" to "pizza_margherita",
                "pizza margherita tk" to "pizza_margherita",
                "pizza fertiggericht" to "pizza",
                "lasagne fertiggericht" to "lasagna",
                "vegetarische lasagne" to "vegetarian_lasagna",
                "fertiggericht gemuesecurry" to "vegetable_curry",
                "chili con carne fertiggericht" to "chili_con_carne",
                "spaghetti bolognese fertiggericht" to "spaghetti_bolognese",
                "gemuesesuppe fertiggericht" to "vegetable_soup",
                "haehnchencurry fertiggericht" to "chicken_curry",
                "ratatouille fertiggericht" to "ratatouille",
                "gulasch fertiggericht" to "goulash",
                "gulasch fertig" to "goulash",
                "erbsensuppe konserve" to "pea_soup",
                "erbsensuppe fertiggericht" to "pea_soup",
                "kartoffelsuppe fertiggericht" to "potato_soup",
                "kartoffelpueree tiefkuehl" to "mashed_potatoes",
                "kartoffelsalat fertiggericht" to "potato_salad",
                "kaesespaetzle fertiggericht" to "cheese_spaetzle",
                "currywurst fertiggericht" to "currywurst",
                "sauerkraut dose" to "sauerkraut",
                "sauerkraut konserve" to "sauerkraut",
                "gruene erbsen dose" to "peas",
                "vegane milchalternative hafer" to "oat_milk",
                "sahneersatz vegan" to "vegan_cream",
                "oliven gruen" to "olives",
                "kokosmilch" to "coconut_milk",
                "eier" to "eggs",
                "joghurt mit fruechten" to "fruit_yogurt",
                "chiasamen" to "chia_seeds",
                "chia samen" to "chia_seeds",
                "leinsamen" to "flaxseed",
                "sesam" to "sesame",
                "hanfsamen" to "hemp_seeds",
                "kokosraspeln" to "desiccated_coconut",
                "mandelkerne" to "almonds",
                "brot weizen" to "bread",
                "kaiserbroetchen" to "bread_roll",
                "maisgriess" to "cornmeal",
                "reis basmati" to "rice",
                "reis vollkorn" to "brown_rice",
                "kuerbis" to "pumpkin",
                "cherrytomaten" to "tomato",
                "rote bete" to "beetroot",
                "chili frisch" to "chili",
                "knoblauch" to "garlic",
                "artischocken" to "artichoke",
                "spargel gruen" to "asparagus",
                "spargel weiss" to "asparagus",
                "zuckerschoten" to "snow_peas",
                "mangold" to "chard",
                "salatmix" to "lettuce",
                "feigen" to "fig",
                "blaubeeren" to "blueberry",
                "schwarze johannisbeeren" to "black_currant",
                "orangen" to "orange",
                "schmand" to "sour_cream",
                "cheddar kaese" to "cheddar",
                "gouda" to "gouda",
                "huettenkaese" to "cottage_cheese",
                "putenwurst" to "turkey_sausage",
                "kasseler" to "smoked_pork",
                "schinken" to "ham",
                "bauernwurst" to "sausage",
                "bruehwurst" to "sausage",
                "haehnchenbrustfilet" to "chicken_breast",
                "rinderhackfleisch" to "minced_beef",
                "kalbsfilet" to "veal_fillet",
                "putenbrust" to "turkey_breast",
                "rohschinken" to "raw_ham",
                "corned beef" to "corned_beef",
                "erbsen in dose" to "peas",
                "kichererbsen in dose" to "chickpeas",
                "thunfisch in dose" to "tuna",
                "matjesfilet" to "herring",
                "honig" to "honey",
                "marmelade" to "jam",
                "ahornsirup" to "maple_syrup",
                "agavendicksaft" to "agave_syrup",
                "eistee" to "iced_tea",
                "kakao" to "cocoa",
                "kakao pulver" to "cocoa_powder",
                "zucker" to "sugar",
                "backpulver" to "baking_powder",
                "frischhefe" to "yeast",
                "vanillezucker" to "vanilla_sugar",
                "vegane schokolade" to "vegan_chocolate",
                "vegane wuerstchen" to "vegan_sausage",
                "vegane frikadellen" to "vegan_patty",
                "kichererbsenmehl" to "chickpea_flour",
                "maisstaerke" to "cornstarch",
                "orange" to "orange",
                "clementine" to "clementine",
                "grapefruit" to "grapefruit",
                "pomelo" to "pomelo",
                "mango" to "mango",
                "papaya" to "papaya",
                "kiwi" to "kiwi",
                "cranberry" to "cranberry",
                "himbeeren" to "raspberry",
                "mirabelle" to "mirabelle",
                "quark magerstufe" to "quark",
                "parmesan" to "parmesan",
                "schnittkaese" to "cheese",
                "frischkaese kraeuter" to "cream_cheese",
                "kaffeesahne" to "coffee_cream",
                "frankfurter" to "frankfurter",
                "bierschinken" to "ham",
                "huehnchenfilet" to "chicken_breast",
                "lammkotelett" to "lamb",
                "rinderbraten" to "beef",
                "schweineschnitzel" to "pork",
                "putensteak" to "turkey",
                "heringsfilet" to "herring",
                "thunfisch in oel" to "tuna",
                "chinakohl" to "chinese_cabbage",
                "schalotten" to "shallots",
                "sellerie knolle" to "celery",
                "birnen" to "pear",
                "soja joghurt" to "soy_yogurt",
                "putenbrustfilet" to "turkey_breast",
                "raeucherlachs" to "salmon",
                "vollkornbroetchen" to "bread_roll",
                "weizenmehl type 405" to "wheat_flour",
                "linguine" to "pasta",
                "vollmilchschokolade" to "milk_chocolate",
                "weisse schokolade" to "white_chocolate",
                "multivitaminsaft" to "multivitamin_juice",
                "bbq sauce" to "barbecue_sauce",
                "kohl" to "cabbage",
                "mandeldrink" to "almond_milk",
                "rindersteak" to "beef",
                "schweinebauch" to "pork_belly",
                "weizenvollkornbrot" to "wholegrain_bread",
                "rundkornreis" to "rice",
                "weisse bohnen in dose" to "white_beans",
                "tomaten in dose" to "tomato",
                "rote linsen" to "red_lentils",
                "buchweizen" to "buckwheat",
                "mandelmus" to "almond_butter",
                "erdnussbutter" to "peanut_butter",
                "erdbuesse" to "peanuts",
                "erdnuesse" to "peanuts",
                "maiskolben" to "corn",
                "gemueseburger" to "vegetable_burger",
                "chili sin carne" to "chili_sin_carne",
                "chili con carne" to "chili_con_carne",
                "nuggets" to "chicken_nuggets",
                "chicken nuggets" to "chicken_nuggets",
                "fruehlingsrollen" to "spring_rolls",
                "maultaschen" to "maultaschen",
                "burger" to "burger",
                "fruchtjoghurt" to "fruit_yogurt",
                "forellenfilet" to "trout",
                "cashewkerne" to "cashews",
                "pflaumen" to "plum",
                "falafel" to "falafel",
                "kuemmel" to "caraway",
                "frikadelle" to "meatball",
                "mandeln" to "almonds",
                "walnuesse" to "walnuts",
                "rotbarschfilet" to "redfish",
                "nelken" to "cloves",
                "kokosjoghurt" to "coconut_yogurt",
                "weintrauben" to "grapes",
                "kardamom" to "cardamom",
                "aprikosen" to "apricot",
                "heidelbeeren" to "blueberry",
                "kartoffelchips" to "chips",
                "schwarzer pfeffer" to "pepper",
                "pfeffer" to "pepper",
                "dickmilch" to "cultured_milk",
                "sellerieknolle" to "celery",
                "tomatenmark" to "tomato_paste",
                "makrele" to "mackerel",
                "thunfischfilet" to "tuna",
                "bachforelle" to "trout",
                "scampi" to "shrimp",
                "champignons" to "mushroom",
                "rote beete" to "beetroot",
                "suesskartoffeln" to "sweet_potato",
                "spinat blatt" to "spinach",
                "waldbeeren" to "mixed_berries",
                "reisdrink" to "rice_milk",
                "sonnenblumenkerne" to "sunflower_seeds",
                "nussmix" to "mixed_nuts",
                "datteln" to "date",
                "pfirsiche" to "peach",
                "kekse" to "cookies",
                "lakritz" to "licorice",
                "aufschnitt" to "cold_cuts",
                "wurstaufschnitt" to "cold_cuts",
                "kaeseaufschnitt" to "cheese",
                "kaesescheiben" to "cheese",
                "kaese" to "cheese",
                "hackfleisch" to "minced_meat",
                "hackfleisch rind" to "minced_beef",
                "hackfleischalternative" to "plant_based_mince",
                "bohnen" to "beans",
                "bohnenmix" to "mixed_beans",
                "gruene erbsen" to "peas",
                "bratwuerste" to "bratwurst",
                "bockwurst" to "sausage",
                "gelbwurst" to "sausage",
                "krakauer wurst" to "sausage",
                "mett" to "minced_pork",
                "fischfilet" to "fish_fillet",
                "schellfischfilet" to "haddock",
                "kabeljau" to "cod",
                "schollenfilet" to "plaice",
                "tintenfischringe" to "squid",
                "koriander" to "coriander",
                "cayennepfeffer" to "cayenne_pepper",
                "pfeffer weiss" to "pepper",
                "rote paprika" to "bell_pepper",
                "kokosdrink" to "coconut_milk",
                "skyr" to "skyr",
                "margarine" to "margarine",
                "pudding" to "pudding",
                "mais" to "corn",
                "kichererbsen" to "chickpeas",
                "linsen" to "lentils",
                "gelbe erbsen" to "peas",
                "weisse bohnen" to "white_beans",
                "haehnchen nuggets" to "chicken_nuggets",
                "tofuwuerfel" to "tofu",
                "sojaschnetzel" to "soy_chunks",
                "fruchtsaft" to "fruit_juice",
                "tomaten ketchup" to "ketchup",
                "glasnudeln" to "glass_noodles",
                "kartoffelknoedel" to "potato_dumplings",
                "kartoffelroesti" to "rosti",
                "erdnussmus" to "peanut_butter",
                "fruchtgummis" to "gummy_candy",
                "knacker wurst" to "sausage",
                "zungenwurst" to "sausage",
                "pastete" to "pate",
                "brotaufstrich" to "spread",
                "brotaufstrich vegetarisch" to "vegetarian_spread",
                "edamame" to "edamame",
                "sauerkraut" to "sauerkraut",
                "couscous" to "couscous",
                "gerste" to "barley",
                "gruenkern" to "green_spelt",
                "haferkleie" to "oat_bran",
                "camembert" to "camembert",
                "schafskaese" to "feta",
                "ziegenkaese" to "goat_cheese",
                "edamame" to "edamame",
                "sauerkraut" to "sauerkraut",
                "couscous" to "couscous",
                "gerste" to "barley",
                "gruenkern" to "green_spelt",
                "haferkleie" to "oat_bran",
                "camembert" to "camembert",
                "schafskaese" to "feta",
                "ziegenkaese" to "goat_cheese",
                "dinkelflocken" to "oats",
                "kamut" to "wheat",
                "weizenkoerner" to "wheat",
                "wilder reis" to "rice",
                "glutenfreie nudeln" to "pasta",
                "auflauf" to "pasta",
                "gratin" to "potato",
                "eintopf" to "potato",
                "schnitzel" to "beef",
                "bratkartoffeln" to "potato",
                "milchreis" to "rice",
                "moussaka" to "potato",
                "basilikum" to "basil",
                "petersilie" to "parsley",
                "dill" to "dill",
                "majoran" to "marjoram",
                "minze" to "mint",
                "rosmarin" to "rosemary",
                "schnittlauch" to "chives",
                "thymian" to "thyme",
                "anis" to "anise",
                "piment" to "allspice",
                "kraeuter der provence" to "thyme",
                "apfelmus" to "apple",
                "apfelsaft" to "apple",
                "apfelschorle" to "apple",
                "apfelchips" to "apple",
                "apfelspalten" to "apple",
                "ingwer" to "ginger",
                "meerrettich" to "horseradish",
                "pfifferlinge" to "chanterelle",
                "avocado" to "avocado",
                "physalis" to "physalis",
                "sauerkirschen" to "sour_cherry",
                "gouda" to "gouda",
                "gouda kaese" to "gouda",
                "gouda jung" to "gouda",
                "gouda kaese reif" to "gouda",
                "edamer" to "edam",
                "edamer kaese" to "edam",
                "kaese edamer" to "edam",
                "emmentaler" to "emmental",
                "emmentaler kaese" to "emmental",
                "kaese emmentaler" to "emmental",
                "feta kaese" to "feta",
                "feta alternative" to "feta",
                "camembert" to "camembert",
                "austernpilze" to "oyster_mushroom",
                "rhabarber" to "rhubarb",
                "bohnen weiss" to "white_beans",
                "erbsen und moehren" to "peas_and_carrots",
                "gemuesemischung" to "vegetable_mix",
                "pommes" to "french_fries",
                "spaetzle" to "spaetzle",
                "kerbel" to "chervil",
                "kresse" to "cress",
                "salbei" to "sage",
                "zitronenmelisse" to "lemon_balm",
                "lauchzwiebeln" to "spring_onion",
                "salatkopf" to "lettuce",
                "erbsenschoten" to "snow_peas",
                "frischmilch" to "milk",
                "vollmilch" to "milk",
                "kuhmilch" to "milk",
                "halbfettmilch" to "milk",
                "hmilch" to "milk",
                "rohmilch" to "milk",
                "sauermilch" to "milk",
                "kondensmilch" to "milk",
                "frischmilch 15" to "milk",
                "frischmilch 35" to "milk",
                "vollmilch 15" to "milk",
                "vollmilch 35" to "milk",
                "kuhmilch 35" to "milk",
                "milch 15" to "milk",
                "milch 35" to "milk",
                "milch 35 fett" to "milk",
                "vollmilch laktosefrei" to "milk",
                "laktosefreie milch" to "milk",
                "bergkaese" to "cheese",
                "butterkaese" to "cheese",
                "hartkaese" to "cheese",
                "weichkaese" to "cheese",
                "naturkaese" to "cheese",
                "vollmilchkaese" to "cheese",
                "grillkaese" to "cheese",
                "handkaese" to "cheese",
                "hirtenkaese" to "cheese",
                "schmierkaese" to "cheese",
                "geriebener kaese" to "cheese",
                "reibekaese" to "cheese",
                "kaese mild" to "cheese",
                "spaghetti vollkorn" to "pasta",
                "vollkornspaghetti" to "pasta",
                "penne nudeln" to "pasta",
                "vollkorn penne" to "pasta",
                "fusilli nudeln" to "pasta",
                "pasta fusilli" to "pasta",
                "spirelli" to "pasta",
                "spirelli nudeln" to "pasta",
                "rigatoni" to "pasta",
                "farfalle" to "pasta",
                "fettuccine" to "pasta",
                "linguine pasta" to "pasta",
                "tagliatelle vollkorn" to "pasta",
                "makkaroni" to "pasta",
                "maccheroni" to "pasta",
                "maccaroni" to "pasta",
                "basmati reis fertiggericht" to "rice",
                "basmati reis weiss" to "rice",
                "basmatireis langkorn" to "rice",
                "biobasmati reis" to "rice",
                "brauner reis" to "rice",
                "brasilienreis" to "rice",
                "glasnudeln reis" to "rice",
                "griechischer langkornreis" to "rice",
                "jasmin reis" to "rice",
                "jasminreis langkorn" to "rice",
                "langkornreis jasmin" to "rice",
                "naturreis" to "rice",
                "naturreis langkorn" to "rice",
                "parboiled langkorn" to "rice",
                "parboiled langkornreis" to "rice",
                "reis basmatireis" to "rice",
                "reis braun" to "rice",
                "reis parboiled" to "rice",
                "reis weiss" to "rice",
                "reisvollkorn" to "rice",
                "risotto reis" to "rice",
                "sushi reis" to "rice",
                "wildreis gemischt" to "rice",
                "wildreis mix" to "rice",
                "wildreismischung" to "rice",
                "naturjoghurt" to "yogurt",
                "griechischer joghurt" to "yogurt",
                "joghurt griechischer art" to "yogurt",
                "joghurt halbfett" to "yogurt",
                "sahnejoghurt" to "yogurt",
                "schafjoghurt" to "yogurt",
                "ziegenjoghurt" to "yogurt",
                "vanillejoghurt" to "yogurt",
                "fruchtjoghurt kirsche" to "yogurt",
                "fruchtjoghurt pfirsich" to "yogurt",
                "trinkjoghurt mango" to "yogurt",
                "trinkjoghurt pfirsich" to "yogurt",
                "magerquark" to "quark",
                "fettarmer quark" to "quark",
                "kraeuterquark" to "quark",
                "quark 20" to "quark",
                "quark 20 fett" to "quark",
                "quark 40" to "quark",
                "quark light" to "quark",
                "speisequark 20" to "quark",
                "speisequark magerstufe" to "quark",
                "sojaquark" to "quark",
                "salat" to "lettuce",
                "salat kopf" to "lettuce",
                "gruener salat" to "lettuce",
                "gemischter salat" to "lettuce",
                "gemischte salate" to "lettuce",
                "blattsalat" to "lettuce",
                "romanasalat" to "lettuce",
                "eisbergsalatkopf" to "lettuce",
                "salatkopf eisberg" to "lettuce",
                "endiviensalat" to "lettuce",
                "schnittsalat" to "lettuce",
                "weinbergsalat" to "lettuce",
                "beeren" to "berries",
                "gemischte beeren" to "berries",
                "gemischtes beerenobst" to "berries",
                "mischung beeren" to "berries",
                "rote beeren" to "berries",
                "rote beeren mix" to "berries",
                "waldbeeren mix" to "berries",
                "waldbeerenmix" to "berries",
                "tiefkuehlbeeren" to "berries",
                "tiefkuehlbeeren mischung" to "berries",
                "tiefkuehlbeerenmix" to "berries",
                "tkbeeren" to "berries",
                "tkbeerenmischung" to "berries",
                "tkbeerenmix" to "berries",
                "gefrorene beeren" to "berries",
                "tomatensosse" to "tomato",
                "tomatensosse dose" to "tomato",
                "tomatensauce klassisch" to "tomato",
                "tomatensauce mit kraeutern" to "tomato",
                "tomatensauce pikant" to "tomato",
                "pasta sauce tomate" to "tomato",
                "tomatenmark tube" to "tomato",
                "tomatensalsa" to "tomato",
                "tomatenketchup" to "tomato",
                // Canned food variants
                "ananasstuecken" to "pineapple",
                "ananasstuecke in dosen" to "pineapple",
                "dosenananas" to "pineapple",

                "dosenbohnen" to "beans",
                "bohnendose" to "beans",
                "eingemachte bohnen" to "beans",

                "dosenchampignons" to "mushroom",
                "champignonkonserve" to "mushroom",
                "dosenerbsen" to "peas",
                "dosenmais" to "corn",
                "dosenpfirsiche" to "peach",
                "dosenpilze" to "mushroom",
                "dosentomaten gehackt" to "tomato",

// Egg variants
                "bauernhof eier" to "egg",
                "bauernhof eier braun" to "egg",
                "bio eier" to "egg",
                "bioeier" to "egg",
                "eier 10 stueck" to "egg",
                "eier bio 6 stueck" to "egg",
                "eier braun" to "egg",
                "eier frei laufend" to "egg",
                "eier freiland" to "egg",
                "eier gross" to "egg",
                "eier weiss" to "egg",
                "freiland eier" to "egg",
                "freilandeier" to "egg",
                "huehnereier" to "egg",
                "wachteleier" to "egg",
                "bruehe gemuese" to "broth",
                "bruehe huhn" to "broth",
                "bruehe rind" to "broth",
                "gemuesebouillon" to "broth",
                "gemuesebruehe" to "broth",
                "gemuesebruehe vegetarisch" to "broth",
                "gemuesebruehe wuerfel" to "broth",
                "gemuesefond" to "broth",
                "huehnerbruehe" to "broth",
                "instantbruehe" to "broth",
                "kraftbruehe" to "broth",
                "knorr gemuesebruehe" to "broth",
                "rinderbruehe" to "broth",
                "eis" to "ice_cream",
                "eis vanille" to "ice_cream",
                "veganes eis" to "ice_cream",
                "veganes eis vanille" to "ice_cream",
                "eiscreme" to "ice_cream",
                "eiscreme schokolade" to "ice_cream",
                "erdbeereis" to "ice_cream",
                "vanilleeis" to "ice_cream",
                "sorbet zitrone" to "ice_cream",
                "hefe" to "yeast",
                "backhefe" to "yeast",
                "hefe frisch" to "yeast",
                "hefe trocken" to "yeast",
                "hefeflocken" to "yeast",
                "hefewuerfel" to "yeast",
                "blaetterteig" to "puff_pastry",
                "blaetterteig tk" to "puff_pastry",
                "blaetterteig tiefgekuehlt" to "puff_pastry",
                "puddingpulver" to "custard_powder",
                "puddingpulver vanille" to "custard_powder",
                "walnusskerne" to "walnut",
                "walnuesse" to "walnut",
                "haselnuesse" to "hazelnut",
                "haselnusskerne" to "hazelnut",
                "cashewnuesse" to "cashew",
                "cashewkerne" to "cashew",
                "rosinen" to "raisin",
                "pflaumen getrocknet" to "prune",
                "trockenpflaumen" to "prune",
                "doerrpflaumen" to "prune",
                "aprikosen getrocknet" to "dried_apricot",
                "trockenmarillen" to "dried_apricot",
                "jakobsmuscheln" to "shellfish",
                "miesmuscheln" to "shellfish",
                "muscheln" to "shellfish",
                "muschelfleisch" to "shellfish",
                "meeresfruechte mix" to "shellfish",
                "austern" to "oyster",
                "krabben" to "shrimp",
                "nordseekrabben" to "shrimp",
                "krabbenfleisch" to "shrimp",
                "garnelen geschaelt" to "shrimp",
                "eismeergarnelen" to "shrimp",
                "shrimps" to "shrimp",
                "suesswasser garnelen" to "shrimp",
                "champignon" to "mushroom",
                "champignon weiss" to "mushroom",
                "champignons braun" to "mushroom",
                "pilze" to "mushroom",
                "pilze geschnitten" to "mushroom",
                "shiitake pilze" to "mushroom",
                "steinpilze" to "mushroom",
                "steinpilze getrocknet" to "mushroom",
                "braune linsen" to "lentils",
                "gelbe linsen" to "lentils",
                "gruene linsen" to "lentils",
                "linsen braun" to "lentils",
                "linsen rot" to "lentils",
                "rote linse" to "lentils",
                "rote linsen getrocknet" to "lentils",
                "rote linsen trocken" to "lentils",
                "schwarze linsen" to "lentils",
                "tuerkische linsen" to "lentils",
                "kichererbsen getrocknet" to "chickpeas",
                "kichererbsen trocken" to "chickpeas",
                "kichererbsen geroestet" to "chickpeas",
                "kichererbsen pueree" to "chickpeas",
                "kichererbsenn" to "chickpeas",
                "bohnen gruen" to "beans",
                "gruene bohnenn" to "beans",
                "gruenen bohnen" to "beans",
                "schwarze bohnen" to "beans",
                "rote bohnen" to "beans",
                "weisse bohnen in tomatensauce" to "beans",
                "pinto bohnen" to "beans",
                "kidneybohnen getrocknet" to "beans",
                "kidneybohnenn" to "beans",
                "erbsen getrocknet" to "peas",
                "gruene erbsen getrocknet" to "peas",
                "gekochte erbsen" to "peas",
                "erbsenn" to "peas",
                "jackfruit konserviert" to "jackfruit",
                "saure gurken" to "pickle",
                "gewuerzgurken" to "pickle",
                "essiggurken" to "pickle",
                "zwetschgen" to "plum",
                "mirabellen" to "plum",
                "limonade" to "lemonade",
                "limonade standard" to "lemonade",
                "remoulade" to "remoulade",
                "remoulade standard" to "remoulade",
                "schokocreme" to "chocolate_spread",
                "vegane schokocreme" to "chocolate_spread",
                "marshmallows" to "marshmallow",
                "marshmallows bio" to "marshmallow",
                "weingummi" to "gummy_candy",
                "weingummi bio" to "gummy_candy",
                "gummibonbons" to "gummy_candy",
                "fruchtgummi" to "gummy_candy",
                "fruchtgummi vegan" to "gummy_candy",
                "erdnussflips" to "peanut_flips",
                "chips" to "potato_chips",
                "chips klassisch" to "potato_chips",
                "chips paprika" to "potato_chips",
                "kartoffelchips" to "potato_chips",
                "kartoffelchips paprika" to "potato_chips",
                "kartoffelchips salz" to "potato_chips",
                "kartoffelchips sour cream" to "potato_chips",
                "kartoffelchips sauerrahm" to "potato_chips",
                "brezel" to "pretzel",
                "brezen" to "pretzel",
                "pretzel" to "pretzel",
                "pretzel sticks" to "pretzel",
                "cracker" to "cracker",
                "saltine cracker" to "cracker",
                "vollkorncracker" to "cracker",
                "sesamcracker" to "cracker",
                "laugencracker" to "cracker",
                "muesliriegel" to "cereal_bar",
                "muesli riegel" to "cereal_bar",
                "proteinriegel" to "cereal_bar",
                "protein riegel" to "cereal_bar",
                "nussriegel" to "cereal_bar",
                "mandelriegel" to "cereal_bar",
                "kartoffelstaebchen" to "potato_sticks",
                "tee" to "tea",
                "chai tee" to "tea",
                "fruechtetee" to "tea",
                "genuss tee" to "tea",
                "gruener tee beutel" to "tea",
                "ingwer tee" to "tea",
                "ingwertee" to "tea",
                "kamillentee" to "tea",
                "kraeutertee" to "tea",
                "matcha tee" to "tea",
                "mate tee" to "tea",
                "matetee" to "tea",
                "minztee" to "tea",
                "pfefferminztee" to "tea",
                "rooibos tee" to "tea",
                "rooibostee" to "tea",
                "schwarzer tee" to "tea",
                "schwarzer tee beutel" to "tea",
                "schwarzer tee lose" to "tea",
                "tee gruener" to "tea",
                "tee kamille" to "tea",
                "zitronentee" to "tea",

                "kaffee" to "coffee",
                "instant kaffee" to "coffee",
                "kaffee bohnen" to "coffee",
                "kaffee creme" to "coffee",
                "kaffee enoffeiniert" to "coffee",
                "kaffee espresso" to "coffee",
                "kaffee filterkaffee" to "coffee",
                "kaffee ganze bohnen" to "coffee",
                "kaffeebohnen" to "coffee",
                "kaffeepads" to "coffee",
                "kaffeepulver" to "coffee",
                "espresso" to "coffee",
                "espressobohnen" to "coffee",
                "gekuehlter orangensaft" to "orange_juice",
                "orangensaft mit fruchtfleisch" to "orange_juice",
                "apfelkirschsaft" to "apple_juice",
                "apfelsaft ohne zucker" to "apple_juice",
                "apfelsaft schorle" to "apple_juice",
                "apfel schorle" to "apple_juice",
                "gemuesesaft" to "vegetable_juice",
                "karottensaft" to "vegetable_juice",
                "rote beete saft" to "vegetable_juice",
                "rote bete saft" to "vegetable_juice",
                "rotebete saft" to "vegetable_juice",
                "selleriesaft" to "vegetable_juice",
                "tomatensaft" to "vegetable_juice",
                "bier alkoholfrei" to "beer",
                "bier pils" to "beer",
                "bieralkoholfrei" to "beer",
                "alkoholfreies bier" to "beer",
                "dunkles bier" to "beer",
                "weissbier" to "beer",
                "weizenbier" to "beer",
                "malzbier" to "beer",
                "radler" to "beer",
                "wein rot trocken" to "wine",
                "wein weiss" to "wine",
                "wein weiss suess" to "wine",
                "rotwein" to "wine",
                "rotwein halbtrocken" to "wine",
                "rotwein trocken" to "wine",
                "weisswein" to "wine",
                "weisswein halbtrocken" to "wine",
                "weisswein trocken" to "wine",
                "cola alkoholfrei" to "cola",
                "cola getraenk" to "cola",
                "cola zero" to "cola",
                "energiedrink" to "energy_drink",
                "energy drink" to "energy_drink",
                "dinkeldrink" to "plant_drink",
                "erbsendrink" to "plant_drink",
                "erdmandeldrink" to "plant_drink",
                "hanfdrink" to "plant_drink",
                "lupinendrink" to "plant_drink",
                "mandel drink schoko" to "plant_drink",
                "peadrink" to "plant_drink",
                "soja drink" to "plant_drink",
                "soja drink ungesuesst" to "plant_drink",
                "dinkelmilch" to "plant_milk",
                "erbsenmilch" to "plant_milk",
                "erbsenproteinmilch" to "plant_milk",
                "hafermilch mit calcium" to "plant_milk",
                "hafermilch ungesuesst" to "plant_milk",
                "hafermilch zuckerfrei" to "plant_milk",
                "hanfdinkelmilch" to "plant_milk",
                "hanfmilch" to "plant_milk",
                "haselnussmilch" to "plant_milk",
                "kokosmilch pflanzlich" to "plant_milk",
                "lupinenmilch" to "plant_milk",
                "macadamiamilch" to "plant_milk",
                "mandelmilch ungesuesst" to "plant_milk",
                "reismilch ungesuesst" to "plant_milk",
                "reismilch schoko" to "plant_milk",
                "sojamilch ungesuesst" to "plant_milk",
                "sojamilch schoko" to "plant_milk",
                "alpro sojajoghurt" to "plant_yogurt",
                "cashew joghurt" to "plant_yogurt",
                "cashewjoghurt" to "plant_yogurt",
                "hafer joghurt" to "plant_yogurt",
                "joghurtalternative kokos" to "plant_yogurt",
                "joghurtalternative mandel" to "plant_yogurt",
                "joghurtalternative soja" to "plant_yogurt",
                "mandeljoghurt ungesuesst" to "plant_yogurt",
                "reis joghurt" to "plant_yogurt",
                "reisjoghurt" to "plant_yogurt",
                "reisjoghurt mit fruechten" to "plant_yogurt",
                "sojajoghurt frucht" to "plant_yogurt",
                "sojayoghurt" to "plant_yogurt",
                "frischkaese alternative" to "vegan_cream_cheese",
                "sojafrischkaese" to "vegan_cream_cheese",
                "kaesealternativen scheiben" to "vegan_cheese",
                "kaeseersatz" to "vegan_cheese",
                "mozzarella alternative" to "vegan_cheese",
                "mozzarella vegan" to "vegan_cheese",
                "streukaese alternative" to "vegan_cheese",
                "barbecue sauce" to "bbq_sauce",
                "barbecuesosse" to "bbq_sauce",
                "bbqsauce" to "bbq_sauce",
                "bbqsosse" to "bbq_sauce",
                "cocktail sauce" to "cocktail_sauce",
                "cocktailketchup" to "cocktail_sauce",
                "cocktailsauce" to "cocktail_sauce",
                "cocktailsosse" to "cocktail_sauce",
                "knoblauch dip" to "garlic_sauce",
                "knoblauch sauce" to "garlic_sauce",
                "knoblauchmayonnaise" to "garlic_sauce",
                "knoblauchsauce" to "garlic_sauce",
                "dressing balsamico" to "salad_dressing",
                "dressing joghurt krauter" to "salad_dressing",
                "dressing joghurtsauce" to "salad_dressing",
                "dressing kraeuter" to "salad_dressing",
                "fertige salatsossen" to "salad_dressing",
                "fertigsalat sauce" to "salad_dressing",
                "honig senf dressing" to "salad_dressing",
                "salatdressing balsamico" to "salad_dressing",
                "salatdressing french" to "salad_dressing",
                "salatdressing joghurt" to "salad_dressing",
                "salatsauce" to "salad_dressing",
                "salatsauce french" to "salad_dressing",
                "salatsauce italienisch" to "salad_dressing",
                "salatsosse" to "salad_dressing",
                "vinaigrette" to "salad_dressing",
                "basler senf" to "mustard",
                "dijon senf" to "mustard",
                "estragon senf" to "mustard",
                "herzhaftes senf" to "mustard",
                "honigsenf" to "mustard",
                "honigsenf sauce" to "mustard",
                "senf dijon" to "mustard",
                "senf grob" to "mustard",
                "senf klassisch" to "mustard",
                "senf koernersenf" to "mustard",
                "senf mittelscharf" to "mustard",
                "senf scharf" to "mustard",
                "senf suess" to "mustard",
                "pesto basilikum" to "pesto",
                "pesto genovese" to "pesto",
                "pesto rosso" to "pesto",
                "pesto verde" to "pesto",
                "apfelessig" to "vinegar",
                "balsamico creme" to "vinegar",
                "balsamico essig" to "vinegar",
                "balsamicoessig" to "vinegar",
                "essig" to "vinegar",
                "essig apfelessig" to "vinegar",
                "essig balsamico" to "vinegar",
                "essig weiss" to "vinegar",
                "himbeeressig" to "vinegar",
                "reisessig" to "vinegar",
                "rotweinessig" to "vinegar",
                "weisser essig" to "vinegar",
                "weisswein essig" to "vinegar",
                "weissweinessig" to "vinegar",
                "mayo vegan" to "vegan_mayonnaise",
                "mayonnaise vegan" to "vegan_mayonnaise",
                "bockshornklee" to "herbs",
                "dill getrocknet" to "herbs",
                "estragon" to "herbs",
                "estragon getrocknet" to "herbs",
                "italienische kraeuter" to "herbs",
                "italienische kraeutermischung" to "herbs",
                "koriander getrocknet" to "herbs",
                "kraeuter" to "herbs",
                "kraeuter mischung" to "herbs",
                "kraeuter petersilie" to "herbs",
                "kraeutermischung" to "herbs",
                "liebstoeckel getrocknet" to "herbs",
                "majoran getrocknet" to "herbs",
                "oregano getrocknet" to "herbs",
                "petersilie getrocknet" to "herbs",
                "pfefferminz getrocknet" to "herbs",
                "rosmarin getrocknet" to "herbs",
                "salbei getrocknet" to "herbs",
                "salbeiblaetter" to "herbs",
                "sauerampfer" to "herbs",
                "thymian getrocknet" to "herbs",
                "bunter pfeffer" to "pepper",
                "pfefferkoerner bunt" to "pepper",
                "pfeffermischung" to "pepper",
                "pfeffermischung bunt" to "pepper",
                "weisser pfeffer" to "pepper",
                "senfkoerner" to "mustard_seed",
                "senfkoerner braun" to "mustard_seed",
                "senfkoerner gelb" to "mustard_seed",
                "senfsaat" to "mustard_seed",
                "senfsamen" to "mustard_seed",
                "himalayasalz" to "salt",
                "meersalz" to "salt",
                "meersalz grob" to "salt",
                "salz grob" to "salt",
                "salz jodiert" to "salt",
                "bbq rub gewuerz" to "spice_mix",
                "braartoffelgewuerz" to "spice_mix",
                "burger gewuerzmischung" to "spice_mix",
                "gelbwurz kurkuma" to "spice_mix",
                "grillgewuerz" to "spice_mix",
                "gyros gewuerz" to "spice_mix",
                "steak pfeffer gewuerz" to "spice_mix",
                "zitrusmix gewuerz" to "spice_mix",
                "salzfrei gewuerzmischung" to "spice_mix",
                "gewuerzmischung italienisch" to "spice_mix",
                "bergwurst" to "bratwurst",
                "bockwurst vegan" to "bratwurst",
                "bratwuerste aus gefluegel" to "bratwurst",
                "bratwurst grob" to "bratwurst",
                "fraenkische bratwurst" to "bratwurst",
                "gefluegelbratwuerstchen" to "bratwurst",
                "gefluegelbratwurst" to "bratwurst",
                "gekochte bratwurst" to "bratwurst",
                "haehnchenbratwurst" to "bratwurst",
                "kalbsbratwurst" to "bratwurst",
                "rinderbratwurst" to "bratwurst",
                "rostbratwurst" to "bratwurst",
                "biosalami" to "salami",
                "italienische salami" to "salami",
                "minisalamis" to "salami",
                "minisalamisnack" to "salami",
                "paprikasalami" to "salami",
                "putensalami" to "salami",
                "salami duenn geschnitten" to "salami",
                "salami grob" to "salami",
                "salami luftgetrocknet" to "salami",
                "salami mild" to "salami",
                "salami scheiben" to "salami",
                "salami vegan" to "salami",
                "wildsalami" to "salami",
                "bauernschinken" to "ham",
                "gekochter schinken" to "ham",
                "geraeucherter schinken" to "ham",
                "kochschinken aufschnitt" to "ham",
                "luftgetrockneter schinken" to "ham",
                "putenschinken" to "ham",
                "raeucherschinken" to "ham",
                "rinderschinken" to "ham",
                "schinkenroh" to "ham",
                "schwarzwalder schinken" to "ham",
                "schwartzwaelder schinken" to "ham",
                "standard schinken" to "ham",
                "bauernleberwurst" to "liver_sausage",
                "delikatessleberwurst" to "liver_sausage",
                "kalbsleberwurst" to "liver_sausage",
                "aufschnitt kraeuter" to "cold_cuts",
                "aufschnittplatten" to "cold_cuts",
                "aufschnittscheiben" to "cold_cuts",
                "frischwurst" to "cold_cuts",
                "gefluegelwurst" to "cold_cuts",
                "kaesewurst" to "cold_cuts",
                "knackwurst" to "cold_cuts",
                "knacker" to "cold_cuts",
                "knacker rohwurst" to "cold_cuts",
                "kochwurst" to "cold_cuts",
                "lyoner" to "cold_cuts",
                "mortadella" to "cold_cuts",
                "raeucherwurst" to "cold_cuts",
                "raeucherwuerstchen" to "cold_cuts",
                "wiener wuerstchen" to "cold_cuts",
                "wienerle" to "cold_cuts",
                "gehacktes gebraten" to "ground_meat",
                "hack" to "ground_meat",
                "hackbaellchen" to "ground_meat",
                "hackbraten" to "ground_meat",
                "hackepeter" to "ground_meat",
                "hackfleisch alternative" to "ground_meat",
                "hackfleisch pute" to "ground_meat",
                "hackfleisch schwein" to "ground_meat",
                "hackfleisch vegan" to "ground_meat",
                "hackfleisch vom rind" to "ground_meat",
                "hackfleisch vom schwein" to "ground_meat",
                "putenhackfleisch" to "ground_meat",
                "rindfleisch gehackt" to "ground_meat",
                "rindfleisch hackfleisch" to "ground_meat",
                "schweinehack" to "ground_meat",
                "schweinehackfleisch" to "ground_meat",
                "bachforellenfilets" to "white_fish",
                "backfisch" to "white_fish",
                "brathering" to "white_fish",
                "dorschfilet" to "white_fish",
                "fischfilet gebacken" to "white_fish",
                "fischfilet gebraten" to "white_fish",
                "fischfilet panier" to "white_fish",
                "fischfilet paniert" to "white_fish",
                "gebackener fisch" to "white_fish",
                "gebackener kabeljau" to "white_fish",
                "heilbutt" to "white_fish",
                "heilbuttfilet" to "white_fish",
                "karpfen" to "white_fish",
                "karpfenfilet" to "white_fish",
                "rotbarsch" to "white_fish",
                "schellfisch" to "white_fish",
                "schelfenfisch" to "white_fish",
                "seeforelle" to "white_fish",
                "seehechtfilet" to "white_fish",
                "seelachs" to "white_fish",
                "seezunge" to "white_fish",
                "seezunge filet" to "white_fish",
                "steinbeisserfilet" to "white_fish",
                "weisser fischfilet" to "white_fish",
                "zanderfilet" to "white_fish",
                "fischfilet lachs" to "fatty_fish",
                "forelle raeucherlachs" to "fatty_fish",
                "graved lachs" to "fatty_fish",
                "lachs geraeuchert scheiben" to "fatty_fish",
                "lachsscheiben" to "fatty_fish",
                "makrelenfilet" to "fatty_fish",
                "raeuchermakrele" to "fatty_fish",
                "rauchlachs" to "fatty_fish",
                "rotlachs" to "fatty_fish",
                "salmon" to "fatty_fish",
                "wildlachsfilet" to "fatty_fish",
                "bismarckhering" to "pickled_herring",
                "eingelegter hering" to "pickled_herring",
                "hering eingelegt" to "pickled_herring",
                "hering in dillsosse" to "pickled_herring",
                "hering in sahnesauce" to "pickled_herring",
                "hering in senfsauce" to "pickled_herring",
                "hering in tomatensauce" to "pickled_herring",
                "hering mariniert" to "pickled_herring",
                "heringfilet" to "pickled_herring",
                "heringsfilets" to "pickled_herring",
                "matjes" to "pickled_herring",
                "matjes hausfrauen art" to "pickled_herring",
                "matjesfilets" to "pickled_herring",
                "fischkonserven" to "canned_fish",
                "makrele in tomatensauce" to "canned_fish",
                "sardinen in tomatensauce" to "canned_fish",
                "sardinen in tomatensosse" to "canned_fish",
                "thunfischkonserve" to "canned_fish",
                "calamari" to "seafood",
                "hummer" to "seafood",
                "kani sticks" to "seafood",
                "kaisergranat" to "seafood",
                "miesmuschelnn" to "seafood",
                "seppia" to "seafood",
                "tintenfisch" to "seafood",
                "fertiggericht" to "ready_meal",
                "fertiggerichte" to "ready_meal",
                "fertigmahlzeit nudeln mit sosse" to "ready_meal",
                "fertigmahlzeit reis mit gemuese" to "ready_meal",
                "nudelgericht fertig" to "ready_meal",
                "pasta mit tomatensosse fertiggericht" to "ready_meal",
                "pancakes fertiggericht" to "ready_meal",
                "pfannkuchen fertig" to "ready_meal",
                "pfannkuchenteig fertiggericht" to "ready_meal",
                "salzburger nockerl fertiggericht" to "ready_meal",
                "sandwich" to "ready_meal",
                "gemuesebratlinge" to "vegetable_patty",
                "vegane gemuesebratlinge" to "vegetable_patty",
                "gemueselaibchen" to "vegetable_patty",
                "gemueselaibchen tk" to "vegetable_patty",
                "gemuesefrikadellen" to "vegetable_patty",
                "gemuesetaler" to "vegetable_patty",
                "bratlinge" to "vegetable_patty",
                "fertig bratlinge vegetarisch" to "vegetable_patty",
                "linsenbratling" to "vegetable_patty",
                "frikadellen vegetarisch" to "vegetable_patty",
                "veganes gyros" to "vegan_gyros",
                "vegetarisches gyros" to "vegan_gyros",
                "seitan gyros" to "vegan_gyros",
                "schnitzel fertiggericht" to "breaded_schnitzel",
                "schnitzel schwein" to "breaded_schnitzel",
                "schnitzel vegetarisch" to "breaded_schnitzel",
                "schnitzel ersatz" to "breaded_schnitzel",
                "jaegerschnitzel" to "breaded_schnitzel",
                "rahmschnitzel" to "breaded_schnitzel",
                "fertige salatmischung" to "prepared_salad",
                "fertiger kartoffelsalat" to "prepared_salad",
                "fertiger reissalat" to "prepared_salad",
                "fertigsalat" to "prepared_salad",
                "fertigsalat mit dressing" to "prepared_salad",
                "fertigsalat mit haehnchen" to "prepared_salad",
                "kartoffelsalat" to "prepared_salad",
                "asia fertiggericht" to "asian_ready_meal",
                "asia nudelpfanne fertiggericht" to "asian_ready_meal",
                "fertiges chicken tikka masala" to "asian_ready_meal",
                "minestrone fertiggericht" to "asian_ready_meal",
                "pad thai" to "asian_ready_meal",
                "paella" to "asian_ready_meal",
                "fertige quiche" to "quiche",
                "quiche" to "quiche",
                "quiche fertig" to "quiche",
                "quiche fertiggericht" to "quiche",
                "quiche vegetarisch" to "quiche",
                "fertiges risotto" to "risotto_ready_meal",
                "gemueserisotto fertiggericht" to "risotto_ready_meal",
                "reis risotto" to "risotto_ready_meal",
                "gebratener reis fertiggericht" to "rice_ready_meal",
                "reis mit gemuese fertiggericht" to "rice_ready_meal",
                "reis schale fertiggericht" to "rice_ready_meal",
                "bio dinkelkekse" to "cookies",
                "butterkeks" to "cookies",
                "butterkekse" to "cookies",
                "dinkelkekse" to "cookies",
                "haferkekse" to "cookies",
                "kekse butter" to "cookies",
                "kekse klassiker" to "cookies",
                "mandelkekse" to "cookies",
                "mehrkornkekse" to "cookies",
                "schokokekse" to "cookies",
                "schokoladenkekse" to "cookies",
                "vollkornkekse" to "cookies",
                "alpenmilchschokolade" to "chocolate",
                "bio vollmilchschokolade" to "chocolate",
                "dunkle schokolade" to "chocolate",
                "mandelschokolade" to "chocolate",
                "milchschokolade" to "chocolate",
                "milchschokolade mit nuessen" to "chocolate",
                "schokolade mit nuessen" to "chocolate",
                "schokolade zartbitter" to "chocolate",
                "schokoladentafel" to "chocolate",
                "schokoladentafel zartbitter" to "chocolate",
                "vollmilch schokolade" to "chocolate",
                "vollmilchschokolade mit nuessen" to "chocolate",
                "zarte vollmilchschokolade" to "chocolate",
                "zartbitterschokolade 85" to "chocolate",
                "zartbitterschokolade mit mandel" to "chocolate",
                "zartbitterschokolade mit nuessen" to "chocolate",
                "zartbitterschokolade mit orange" to "chocolate",
                "zartbitterschokolade pur" to "chocolate",
                "zartbitterschokolade vegan" to "chocolate",
                "nougat pralinen" to "pralines",
                "nougatpralinen" to "pralines",
                "pralinen" to "pralines",
                "erdbeerkonfituere" to "jam",
                "fruchtmarmelade" to "jam",
                "fruchtmarmelade aprikose" to "jam",
                "himbeermarmelade" to "jam",
                "marmelade aprikose" to "jam",
                "marmelade himbeere" to "jam",
                "nussnougatcreme" to "jam",
                "nougatcreme" to "jam",
                "orangenmarmelade" to "jam",
                "pfirsichmarmelade" to "jam",
                "pflaumenmus" to "jam",
                "pflaumenmus glas" to "jam",
                "pflaumenmus ohne zucker" to "jam",
                "schokoladencreme" to "jam",
                "butterkuchen" to "cake",
                "dinkeltorte" to "cake",
                "honigkuchen" to "cake",
                "kuchen klassisch" to "cake",
                "kuchen schoko" to "cake",
                "kuchenklassiker" to "cake",
                "muffins" to "cake",
                "vanillekipferl" to "cake",
                "weihnachtsplaetzchen" to "cake",
                "butterhoernchen" to "pastry",
                "hefezopf" to "pastry",
                "kaisersemmel" to "pastry",
                "kaisersemmeln" to "pastry",
                "kornspitz" to "pastry",
                "laugengipfel" to "pastry",
                "laugenstangen" to "pastry",
                "wraps" to "pastry",
                "tortilla wraps" to "pastry",
                "gelee bonbons" to "candy",
                "honig bonbons" to "candy",
                "honigbonbons" to "candy",
                "karamellbonbons" to "candy",
                "lutschbonbons" to "candy",
                "pfefferminzbonbons" to "candy",
                "toffees" to "candy",
                "toffifee" to "candy",
                "zuckerfrei bonbons" to "candy",
                "energieriegel" to "chocolate_bar",
                "kokosriegel" to "chocolate_bar",
                "marsriegel" to "chocolate_bar",
                "reiswaffel mit schokolade" to "chocolate_bar",
                "reiswaffeln mit schokolade" to "chocolate_bar",
                "schokoladenriegel" to "chocolate_bar",
                "zartbitterschokoladenriegel" to "chocolate_bar",
                "gemischtes gemuese" to "mixed_vegetables",
                "gemischtes tiefkuehlgemuese" to "mixed_vegetables",
                "gemischtes tkgemuese" to "mixed_vegetables",
                "gemischtes gemuese tk" to "mixed_vegetables",
                "gemuese" to "mixed_vegetables",
                "gefrorenes gemuese" to "mixed_vegetables",
                "deep frozen gemuese" to "mixed_vegetables",
                "fertiger gemuesemix" to "mixed_vegetables",
                "gemuesemischung asiatisch" to "mixed_vegetables",
                "gemuese mischung" to "mixed_vegetables",
                "gemuesemischung" to "mixed_vegetables",
                "gemuese pfanne" to "mixed_vegetables",
                "pfannengemuese" to "mixed_vegetables",
                "bratgemuese" to "mixed_vegetables",
                "grillgemuese" to "mixed_vegetables",
                "zweite wahl gemuese" to "mixed_vegetables",
                "babyspinat" to "leafy_greens",
                "babyspinat frisch" to "leafy_greens",
                "brunnenkresse" to "leafy_greens",
                "fruehlingszwiebeln" to "leafy_greens",
                "gruenkohl" to "leafy_greens",
                "mangold glatt" to "leafy_greens",
                "radicchio" to "leafy_greens",
                "rucolasalat" to "leafy_greens",
                "selleriestangen" to "leafy_greens",
                "stangensellerie" to "leafy_greens",
                "weisser spargel" to "leafy_greens",
                "gruener spargel" to "leafy_greens",
                "gruene spargelstangen" to "leafy_greens",
                "wirsing" to "leafy_greens",
                "wirz" to "leafy_greens",
                "cocktailtomaten" to "tomato",
                "cocktailtomaten frisch" to "tomato",
                "tomaten cherrys" to "tomato",
                "tomaten kirsche" to "tomato",
                "tomaten reif" to "tomato",
                "gelbe paprika" to "tomato",
                "gruene paprika" to "tomato",
                "paprikaschoten" to "tomato",
                "rote paprika" to "tomato",
                "strauchtomaten" to "tomato",
                "apfelsine" to "apple",
                "gruener apfel" to "apple",
                "gruene aepfel" to "apple",
                "rote aepfel" to "apple",
                "birnenkompott" to "pear",
                "cranberries getrocknet" to "dried_fruit",
                "datteln getrocknet" to "dried_fruit",
                "feigen getrocknet" to "dried_fruit",
                "trockenfruechte mischung" to "dried_fruit",
                "trockenfruechte mix" to "dried_fruit",
                "dinkelgriess" to "spelt",
                "dinkelkleie" to "spelt",
                "dinkelkoerner" to "spelt",
                "dinkelmehl" to "spelt",
                "dinkelmehl type 630" to "spelt",
                "dinkelschrot" to "spelt",
                "dinkelspelz" to "spelt",
                "dinkelvollkornmehl" to "spelt",
                "buchweizenmehl" to "buckwheat",
                "buchweizennudeln" to "buckwheat",
                "weizenmehl typ 405" to "wheat_flour",
                "weizenmehl typ 550" to "wheat_flour",
                "weizenmehl type 550" to "wheat_flour",
                "weizenmehl typ 1050" to "wheat_flour",
                "weizenmehl type 1050" to "wheat_flour",
                "weizenmehl vollkorn" to "wholegrain_flour",
                "weizenvollkornmehl type 1050" to "wholegrain_flour",
                "vollkornmehl" to "wholegrain_flour",
                "roggenmehl type 1150" to "wholegrain_flour",
                "roggenvollkornmehl" to "wholegrain_flour",
                "griess hartweizen" to "semolina",
                "griessbrei" to "semolina",
                "grober maisgriess" to "semolina",
                "weizengriess" to "semolina",
                "gerstenflocken" to "barley",
                "gerstengraupen" to "barley",
                "gerstengruetze" to "barley",
                "gerstenmalz" to "barley",
                "gerstenmalzextrakt" to "barley",
                "graupen" to "barley",
                "hirse gepufft" to "millet",
                "hirse geschaelt" to "millet",
                "hirseflocken" to "millet",
                "hirsemehl" to "millet",
                "maismehl gelb" to "cornmeal",
                "maisschrot" to "cornmeal",
                "maisstaerke" to "cornmeal",
                "maizena maisstaerke" to "cornmeal",
                "glutenfreie mehlmischung" to "gluten_free_flour",
                "glutenfreies mehl" to "gluten_free_flour",
                "kamutmehl" to "ancient_grain",
                "kamut nudeln" to "ancient_grain",
                "teff" to "ancient_grain",
                "teffmehl" to "ancient_grain",
                "sorghum" to "ancient_grain",
                "zartweizen" to "ancient_grain",
                "zartweizenmehl" to "ancient_grain",
                "haehnchenbrustfilet mariniert" to "chicken",
                "haehnchenfilet" to "chicken",
                "haehnchenfluegel" to "chicken",
                "haehnchenhackfleisch" to "chicken",
                "haehnchenleber" to "chicken",
                "haehnchenschenkel" to "chicken",
                "huehnerbrust" to "chicken",
                "huehnerleber" to "chicken",
                "gefluegelbrust" to "chicken",
                "gefluegelbrustfilet" to "chicken",
                "gefluegelhackfleisch" to "chicken",
                "gefluegelleber" to "chicken",
                "bioputenbrust" to "turkey",
                "putenbraten" to "turkey",
                "putenbrust aufschnitt" to "turkey",
                "putenbrustaufschnitt" to "turkey",
                "putenfleisch gewuerfelt" to "turkey",
                "putenkeule" to "turkey",
                "putenkeulen" to "turkey",
                "putenoberkeule" to "turkey",
                "putenschnitzel" to "turkey",
                "schweinebauch scheiben" to "pork",
                "schweinebraten" to "pork",
                "schweinebraten fertiggericht" to "pork",
                "schweinefleisch hackfleisch" to "pork",
                "schweinefleisch nacken" to "pork",
                "schweinekarree" to "pork",
                "schweinekotelett" to "pork",
                "schweinekoteletts" to "pork",
                "schweineleber" to "pork",
                "schweinemett" to "pork",
                "schweineschulter" to "pork",
                "rippchen schwein" to "pork",
                "beinscheibe rind" to "beef",
                "rinderfiletsteak" to "beef",
                "rinderleber" to "beef",
                "rinderroulade" to "beef",
                "rinderrouladen" to "beef",
                "rindfleisch geschnitten" to "beef",
                "rindfleisch steak" to "beef",
                "rindsrouladen" to "beef",
                "roastbeef" to "beef",
                "roastbeefaufschnitt" to "beef",
                "kalbsbraten" to "veal",
                "kalbschnitzel" to "veal",
                "kalbsfleisch" to "veal",
                "kalbsfleisch geschnetzeltes" to "veal",
                "kalbshackfleisch" to "veal",
                "kalbshaxe" to "veal",
                "kalbsleber" to "veal",
                "kalbsrahmgeschnetzeltes" to "veal",
                "kalbsruecken" to "veal",
                "kalbsschnitzel" to "veal",
                "kalbssteak" to "veal",
                "lammkeule" to "lamb",
                "lammkoteletts" to "lamb",
                "entenbrust" to "duck",
                "entenbrustfilet" to "duck",
                "entenkeule" to "duck",
                "gaensebrust" to "duck",
                "gaensebrustfilet" to "duck",
                "gaensekeule" to "duck",
                "wildente" to "duck",
                "wildentenbrust" to "duck",
                "hirschbraten" to "game_meat",
                "hirschfleisch" to "game_meat",
                "hirschsteak" to "game_meat",
                "kaninchen" to "game_meat",
                "kaninchenfleisch" to "game_meat",
                "pferdefleisch" to "game_meat",
                "rebhuhn" to "game_meat",
                "rehmedaillons" to "game_meat",
                "wachtelbrust" to "game_meat",
                "wildfleisch gemischt" to "game_meat",
                "wildhackfleisch" to "game_meat",
                "wildschwein" to "game_meat",
                "wildschweinbraten" to "game_meat",
                "wildschweinfilet" to "game_meat",
                "wildschweinfleisch" to "game_meat",
                "wildschweinkeule" to "game_meat",
                "bacon" to "bacon",
                "fruehstuecksspeck" to "bacon",
                "raeucherspeck" to "bacon",
                "speck" to "bacon",
                "speckwuerfel" to "bacon",
                "sauce hollandaise" to "hollandaise_sauce",
                "sauce hollandaise in dose" to "hollandaise_sauce",
                "sauce hollandaise fertig" to "hollandaise_sauce",
                "hollaendische sauce" to "hollandaise_sauce",
                "barnaise sauce" to "bearnaise_sauce",
                "alfredo sauce" to "alfredo_sauce",
                "kaesesauce" to "alfredo_sauce",
                "teriyaki sauce" to "teriyaki_sauce",
                "teriyakisauce" to "teriyaki_sauce",
                "scharfe sauce" to "hot_sauce",
                "sriracha sauce" to "hot_sauce",
                "tabasco sauce" to "hot_sauce",
                "tzatziki sauce" to "tzatziki",
                "sauerrahm dip" to "tzatziki",
                "sauerrahm dressing" to "tzatziki",
                "salsa sauce" to "salsa_sauce",
                "maissalsa" to "salsa_sauce",
                "fischsauce" to "fish_sauce",
                "shoyu sojasauce" to "soy_sauce",
                "sojasauce dunkel" to "soy_sauce",
                "sojasauce glutenfrei" to "soy_sauce",
                "sojasauce hell" to "soy_sauce",
                "sojasauce salzarm" to "soy_sauce",
                "sojasosse" to "soy_sauce",
                "worcestersauce" to "worcestershire_sauce",
                "cremiger frischkaese" to "fresh_cheese",
                "doppelrahmfrischkaese" to "fresh_cheese",
                "frischkaese natur" to "fresh_cheese",
                "frischkaese kraeuter" to "fresh_cheese",
                "ziegenfrischkaese" to "fresh_cheese",
                "feta" to "feta",
                "schafskaese" to "feta",
                "edelpilzkaese" to "blue_cheese",
                "gorgonzola" to "blue_cheese",
                "roquefort" to "blue_cheese",
                "bueffelmozzarella" to "mozzarella",
                "mozzarella di bufala" to "mozzarella",
                "vollmilch mozzarella" to "mozzarella",
                "mozzarella sticks" to "mozzarella",
                "brie" to "hard_cheese",
                "emmentaler" to "hard_cheese",
                "emmentaler kaese" to "hard_cheese",
                "gauda jung" to "hard_cheese",
                "gauda mittelalt" to "hard_cheese",
                "gruyere" to "hard_cheese",
                "leerdammer" to "hard_cheese",
                "maasdamer" to "hard_cheese",
                "parmesan" to "hard_cheese",
                "pecorino" to "hard_cheese",
                "rohmilchkaese" to "hard_cheese",
                "tilsiter" to "hard_cheese",
                "tilsiter kaese" to "hard_cheese",
                "weidenkorbkaese" to "hard_cheese",
                "buttermilch" to "buttermilk",
                "buttermilchkulturen" to "buttermilk",
                "kaffeesahne" to "cream",
                "kochsahne" to "cream",
                "sahne zum kochen" to "cream",
                "sahne zum schlagen" to "cream",
                "schlagsahne lactosefrei" to "cream",
                "vollmilch schlagsahne" to "cream",
                "saure sahne" to "cream",
                "sauerrahm" to "cream",
                "schmand" to "cream",
                "kefir naturell" to "kefir",
                "kefir mit fruechten" to "kefir",
                "fermentierter tofu" to "tofu",
                "geraeucherter tofu" to "tofu",
                "marinierter tofu" to "tofu",
                "naturtofu" to "tofu",
                "raeuchertofu" to "tofu",
                "seidentofu" to "tofu",
                "sahnetofu" to "tofu",
                "tofu aufschnitt" to "tofu",
                "tofu burger patties" to "tofu",
                "tofu geschnetzeltes" to "tofu",
                "tofu raeuchertofu" to "tofu",
                "tofu schnitzel" to "tofu",
                "tofu wuerfel" to "tofu",
                "tofu wuerstchen" to "tofu",
                "tofufilet" to "tofu",
                "tofuhack" to "tofu",
                "tofuruehrei vegan" to "tofu",
                "tofusalami" to "tofu",
                "tofusalat" to "tofu",
                "tofustreifen mariniert" to "tofu",
                "tofuwuerfel mariniert" to "tofu",
                "tofuwuerstchen" to "tofu",
                "tofuwurst" to "tofu",
                "quorn stuecke" to "plant_based_meat",
                "fleischalternative" to "plant_based_meat",
                "sojafleisch" to "plant_based_meat",
                "sojahack" to "plant_based_meat",
                "sojawuerfel" to "plant_based_meat",
                "sojawuerstchen" to "plant_based_meat",
                "sojawurst vegan" to "plant_based_meat",
                "seitan geschnitten" to "seitan",
                "seitan mariniert" to "seitan",
                "seitanaufschnitt" to "seitan",
                "seitanbraten" to "seitan",
                "seitanstuecke" to "seitan",
                "seitanwuerstchen" to "seitan",
                "tempeh mariniert" to "tempeh",
                "hummus" to "hummus",
                "humus" to "hummus",
                "lebensmittel hummus" to "hummus",
                "falafel fertig" to "falafel",
                "falafel vegan" to "falafel",
                "gemuese burger" to "veggie_burger",
                "gemueseburger vegan" to "veggie_burger",
                "kichererbsen burger patties" to "veggie_burger",
                "veggie burger" to "veggie_burger",
                "veggie nuggets" to "veggie_burger",
                "veggieburger" to "veggie_burger",
                "veggieburger patty" to "veggie_burger",
                "veggiepatty" to "veggie_burger",
                "aufstrich" to "plant_spread",
                "aufstriche" to "plant_spread",
                "hefeextrakt aufstrich" to "plant_spread",
                "streichcreme" to "plant_spread",
                "vegetarischer aufstrich" to "plant_spread",
                "vegane aufstriche" to "plant_spread",
                "bulgur fertiggericht" to "bulgur",
                "bulgur salat vegetarisch" to "bulgur",
                "couscous mit gemuese" to "couscous",
                "couscous vollkorn" to "couscous",
                "kuszkus" to "couscous",
                "vollkorn couscous" to "couscous",
                "gnocchi" to "gnocchi",
                "kartoffelgnocchi" to "gnocchi",
                "ravioli" to "ravioli",
                "ravioli in tomatensauce" to "ravioli",
                "tortellini" to "tortellini",
                "tortellini fertig" to "tortellini",
                "tortellini mit kaesefuellung" to "tortellini",
                "dumplings" to "dumplings",
                "dumplings tk" to "dumplings",
                "biospaetzle" to "spaetzle",
                "kaese spaetzle fertiggericht" to "spaetzle",
                "spaetzle" to "spaetzle",
                "brotkrumen" to "bread_crumbs",
                "brorumen" to "bread_crumbs",
                "brotkruste" to "bread_crumbs",
                "broruste" to "bread_crumbs",
                "semmelbroesel" to "bread_crumbs",
                "bandnudeln eier" to "pasta",
                "bavette nudeln" to "pasta",
                "bio eiernudeln" to "pasta",
                "dinkelnudeln" to "pasta",
                "dinkelspaghetti" to "pasta",
                "ditalini nudeln" to "pasta",
                "dreierlei nudeln" to "pasta",
                "duenne eiernudeln" to "pasta",
                "duenne spaghetti" to "pasta",
                "eiernudeln breit" to "pasta",
                "eierteigwaren" to "pasta",
                "eiweissnudeln" to "pasta",
                "fadennudeln" to "pasta",
                "glutenfreie fusilli" to "pasta",
                "glutenfreie nudeln fusilli" to "pasta",
                "glutenfreie penne" to "pasta",
                "glutenfreie spaghetti" to "pasta",
                "instantnudeln" to "pasta",
                "kichererbsennudeln" to "pasta",
                "kochnudeln" to "pasta",
                "kuerbiskernnudeln" to "pasta",
                "kuerbisnudeln" to "pasta",
                "linsen nudeln" to "pasta",
                "linsen pasta" to "pasta",
                "linsennudeln" to "pasta",
                "linsenpasta" to "pasta",
                "mienudeln" to "pasta",
                "mueslinudeln" to "pasta",
                "nudelmischung" to "pasta",
                "nudeln mit ei" to "pasta",
                "nudeln spaghetti weiss" to "pasta",
                "nudeln spirelli" to "pasta",
                "nudelteig" to "pasta",
                "pennernudeln" to "pasta",
                "pho nudeln" to "pasta",
                "reisnudeln breit" to "pasta",
                "reisnudeln vollkorn" to "pasta",
                "ricciarelli nudeln" to "pasta",
                "ricettanudeln" to "pasta",
                "rote linsen nudeln" to "pasta",
                "rote linsen pasta" to "pasta",
                "sobanudeln" to "pasta",
                "tagliolini" to "pasta",
                "teigwaren" to "pasta",
                "teigwaren bandnudeln" to "pasta",
                "weizennudeln" to "pasta",
                "mandelblaettchen" to "almond",
                "mandelblaetter" to "almond",
                "mandelkerne" to "almond",
                "mandelmus" to "almond",
                "mandelstifte" to "almond",
                "mandelsplitter" to "almond",
                "geroestete mandeln" to "almond",
                "mandeln geroestet" to "almond",
                "pistazien geroestet" to "pistachio",
                "pistazien gesalzen" to "pistachio",
                "pistazienkerne" to "pistachio",
                "pistazienmus" to "pistachio",
                "sonnenblumenkerne" to "sunflower_seed",
                "sonnenblumenkerne geroestet" to "sunflower_seed",
                "sonnenblumenkerne gesalzen" to "sunflower_seed",
                "kuerbiskerne" to "pumpkin_seed",
                "kuerbiskerne geroestet" to "pumpkin_seed",
                "kuerbiskernmix" to "pumpkin_seed",
                "kuerbiskernmus" to "pumpkin_seed",
                "sesam geroestet" to "sesame",
                "sesam schwarz" to "sesame",
                "sesam weiss" to "sesame",
                "sesamkoerner" to "sesame",
                "leinsamen ganz" to "flaxseed",
                "leinsamen geschrotet" to "flaxseed",
                "goldleinsamen" to "flaxseed",
                "braune leinsamen" to "flaxseed",
                "chia" to "chia_seed",
                "chia samen" to "chia_seed",
                "chia saat" to "chia_seed",
                "sesampaste" to "tahini",
                "tahin" to "tahini",
                "tahin" to "tahini",
                "tahinipaste" to "tahini",
                "kokoswasser" to "coconut_water",
                "kokoswasser bio" to "coconut_water",
                "kokoswasser natur" to "coconut_water",
                "cranberrysaft" to "cranberry_juice",
                "cranberry muttersaft" to "cranberry_juice",
                "cranberry schorle" to "cranberry_juice",
                "granatapfelsaft" to "pomegranate_juice",
                "granatapfel muttersaft" to "pomegranate_juice",
                "multivitaminsaft" to "multivitamin_juice",
                "multivitamin drink" to "multivitamin_juice",
                "vitaminsaft" to "multivitamin_juice",
                "ace saft" to "multivitamin_juice",
                "ace drink" to "multivitamin_juice",
                "beeren smoothie" to "smoothie",
                "erdbeer smoothie" to "smoothie",
                "frucht smoothie" to "smoothie",
                "gemuese smoothie" to "smoothie",
                "gruener smoothie" to "smoothie",
                "mango smoothie" to "smoothie",
                "protein smoothie" to "smoothie",
                "smoothie bowl" to "smoothie",
                "superfood smoothie" to "smoothie",
                "apfelwein" to "cider",
                "cidre" to "cider",
                "birnen cidre" to "cider",
                "birnenwein" to "cider",
                "mineralwasser classic" to "sparkling_water",
                "mineralwasser medium" to "sparkling_water",
                "mineralwasser sprudel" to "sparkling_water",
                "sprudelwasser" to "sparkling_water",
                "eistee pfirsich" to "iced_tea",
                "eistee zitrone" to "iced_tea",
                "gruener eistee" to "iced_tea",
                "ice tea" to "iced_tea",
                "pfirsich eistee" to "iced_tea",
                "zitronen eistee" to "iced_tea",
                "zimt" to "cinnamon",
                "zimtpulver" to "cinnamon",
                "cassia zimt" to "cinnamon",
                "ceylon zimt" to "cinnamon",
                "zimt gemahlen" to "cinnamon",
                "zimtstangen" to "cinnamon",
                "vanille" to "vanilla",
                "bourbon vanille" to "vanilla",
                "vanille gemahlen" to "vanilla",
                "vanillepulver" to "vanilla",
                "vanilleschote" to "vanilla",
                "vanilleschoten" to "vanilla",
                "vanillezucker" to "vanilla",
                "lorbeer" to "bay_leaf",
                "lorbeerblaetter" to "bay_leaf",
                "lorbeerblatt" to "bay_leaf",
                "sternanis" to "star_anise",
                "anissterne" to "star_anise",
                "muskat" to "nutmeg",
                "muskatnuss" to "nutmeg",
                "muskat gemahlen" to "nutmeg",
                "muskatnuesse" to "nutmeg",
                "edelsuess paprika" to "paprika_powder",
                "paprika edelsuess" to "paprika_powder",
                "paprika rosenscharf" to "paprika_powder",
                "paprikapulver" to "paprika_powder",
                "paprikagewuerz" to "paprika_powder",
                "curry" to "curry_powder",
                "currypulver" to "curry_powder",
                "curry indisch" to "curry_powder",
                "madras curry" to "curry_powder",
                "kurkuma" to "turmeric",
                "gelbwurz" to "turmeric",
                "kurkumapulver" to "turmeric",
                "kreuzkuemmel" to "cumin",
                "kreuzkuemmel gemahlen" to "cumin",
                "cumin gemahlen" to "cumin",
                "cumin samen" to "cumin",
                "knoblauchpulver" to "garlic_powder",
                "knoblauch granulat" to "garlic_powder",
                "knoblauch granulat" to "garlic_powder",
                "knoblauch gewuerz" to "garlic_powder",
                // Frequent OFF aliases
                "ice cream" to "ice_cream",
                "premium ice cream" to "ice_cream",
                "potato chips" to "potato_chips",
                "comt" to "comte",
                "emmental" to "emmental",
                "tomato ketchup" to "ketchup",
                "cookies" to "cookies",
                "sparkling water beverage" to "sparkling_water",
                "tomato sauce" to "tomato_sauce",
                "creamy peanut butter" to "peanut_butter",
                "apple sauce" to "apple",
                "potato chips" to "potato_chips",
                "premium ice cream" to "ice_cream",
                "extra virgin olive oil" to "olive_oil",
                "emmental cheese" to "emmental",
                "beef jerky" to "beef_jerky",
                "pinto beans" to "pinto_beans",
                "milk chocolate" to "milk_chocolate",
                "sparkling water" to "sparkling_water",
                "tomato sauce" to "tomato_sauce",
                "creamy peanut butter" to "peanut_butter",
                "peanut butter" to "peanut_butter",
                "black beans" to "black_beans",
                "dark chocolate" to "dark_chocolate",
                "almond" to "almonds",
                "granola cereal" to "granola",
                "cottage cheese" to "cottage_cheese",
                "trail mix" to "trail_mix",
                "green tea" to "green_tea",
                "iced tea" to "iced_tea",
                "apple sauce" to "apple",
                "tomato ketchup" to "ketchup",
                "sparkling water beverage" to "sparkling_water",
                "bananes" to "banana",
                "applesauce" to "apple",
                "olive oil" to "olive_oil",
                "orange juice" to "orange_juice",
                "yellow mustard" to "mustard",
                "real mayonnaise" to "mayonnaise",
                "crunchy peanut butter" to "peanut_butter",
                "seltzer water" to "sparkling_water",
                "pasta sauce" to "tomato_sauce",
                "greek yogurt" to "yogurt",
                "greek nonfat yogurt" to "yogurt",
                "nonfat yogurt" to "yogurt",
                "lowfat yogurt" to "yogurt",
                "whole milk" to "milk",
                "fat free milk" to "milk",
                "2 reduced fat milk" to "milk",
                "1 lowfat milk" to "milk",
                "aceite de oliva virgen extra" to "olive_oil",
                "aceite de oliva" to "olive_oil",
                "huile d olive vierge extra" to "olive_oil",
                "huile d olive" to "olive_oil",
                "miel" to "honey",
                "miel de fleurs" to "honey",
                "miel d acacia" to "honey",
                "jus de pomme" to "apple_juice",
                "jus d orange" to "orange_juice",
                "chocolat" to "chocolate",
                "chocolat au lait" to "milk_chocolate",
                "chocolat noir" to "dark_chocolate",
                "agua mineral natural" to "water",
                "pois chiches" to "chickpeas",
                "noix de cajou" to "cashews",
                "caf" to "coffee",
                "moutarde de dijon" to "mustard",
                "yaourt nature" to "yogurt",
                "filet de poulet" to "chicken",
                "filets de poulet" to "chicken",
                "filets de poulet r ti" to "chicken",
                "poulet" to "chicken",
                "aiguillettes de poulet" to "chicken",
                "escalope de dinde" to "turkey",
                "parmigiano reggiano" to "parmesan",
                "grana padano" to "parmesan",
                "emmental fran ais" to "emmental",
                "reblochon de savoie" to "reblochon",
                "pain complet" to "wholegrain_bread",
                "pain" to "bread",
                "pain au chocolat" to "pastry",
                "reblochon de savoie" to "reblochon",
                "emmental francais" to "emmental",
                "sharp cheddar cheese" to "cheddar",
                "mozzarella cheese" to "mozzarella",
                "cut green beans" to "green_beans",
                "sweet peas" to "peas",
                "diced tomatoes" to "tomato",
                "mixed nuts" to "nuts",
                "peanuts" to "peanuts",
                "canola oil" to "rapeseed_oil",
                "vegetable oil" to "vegetable_oil",
                "coconut water" to "coconut_water",
                "jam" to "jam"
            )
    }
}