package de.shopme.tools.knowledge.ki_candidates

enum class KnowledgeDimensionCandidateType {

    NUTRITION,
    NUTRI_SCORE,
    CARBON,
    DIET,
    WATER,
    WATER_STRESS,
    GLYCEMIC,
    ALLERGENS,
    INGREDIENTS,
    TAXONOMY,
    SEASONALITY,
    PACKAGING,
    FAIRTRADE,
    ANIMAL_WELFARE,
    BIODIVERSITY,
    POLLINATOR,
    LOCALITY,
    FOOD_MILES,
    PRODUCTION,
    RECIPE,
    INGREDIENT_GRAPH,
    RECIPE_GRAPH,
    CARBON_IMPACT,
    PESTICIDES,
    PROCESSING,
    ENVIRONMENTAL_IMPACT
}