package de.shopme.presentation.developer.report

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import de.shopme.ui.theme.BrandCreme

@Composable
fun BuildReportScreen(

    onClose: () -> Unit,

    provider: BuildReportProvider =
        DefaultBuildReportProvider()

) {

    val report = remember {

        provider.report()

    }

    Surface(

        modifier = Modifier.fillMaxSize(),

        color = BrandCreme

    ) {

        Column(

            modifier = Modifier

                .padding(24.dp)

                .verticalScroll(

                    rememberScrollState()

                )

        ) {


            Row(

                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 16.dp),

                horizontalArrangement = Arrangement.SpaceBetween,

                verticalAlignment = Alignment.CenterVertically

            ) {

                Text(

                    text = "← Schließen",

                    style = MaterialTheme.typography.titleMedium,

                    modifier = Modifier.clickable {

                        onClose()

                    }

                )

            }

            Text(

                text = "📊 Build Report",

                style = MaterialTheme.typography.headlineMedium

            )

            Text(

                text = "Knowledge Compiler",

                style = MaterialTheme.typography.titleMedium

            )

            HorizontalDivider(

                modifier = Modifier.padding(vertical = 16.dp)

            )

            Text(

                text = "Sections: ${report.summary.sections}",

                style = MaterialTheme.typography.bodyMedium

            )

            Text(

                text = "Artifacts: ${report.summary.artifacts}",

                style = MaterialTheme.typography.bodyMedium

            )

            Text(

                text = "Entries: ${report.summary.totalEntries}",

                style = MaterialTheme.typography.bodyMedium

            )

            HorizontalDivider(

                modifier = Modifier.padding(vertical = 16.dp)

            )

            report.sections.forEach { section ->

                Text(

                    text = section.title.uppercase(),

                    style = MaterialTheme.typography.titleMedium,

                    modifier = Modifier.padding(top = 16.dp)

                )

                HorizontalDivider(

                    modifier = Modifier.padding(vertical = 8.dp)

                )

                section.entries.forEach { entry ->

                    Row(

                        modifier = Modifier

                            .fillMaxWidth()

                            .padding(vertical = 6.dp),

                        horizontalArrangement =

                            Arrangement.SpaceBetween

                    ) {

                        Text(

                            text = entry.name,

                            style = MaterialTheme.typography.bodyLarge

                        )

                        Text(

                            text = entry.count.toString(),

                            style = MaterialTheme.typography.bodyLarge

                        )

                    }

                }

            }

            HorizontalDivider(

                modifier = Modifier.padding(vertical = 16.dp)

            )

            Text(

                text =

                    "Generated by Hivra Knowledge Compiler",

                style = MaterialTheme.typography.labelMedium

            )

        }

    }

}